// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package vacancy

import (
	models "github.com/go-park-mail-ru/2020_2_MVVM.git/models/models"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// IUseCaseVacancy is an autogenerated mock type for the IUseCaseVacancy type
type IUseCaseVacancy struct {
	mock.Mock
}

// AddFavorite provides a mock function with given fields: _a0
func (_m *IUseCaseVacancy) AddFavorite(_a0 models.FavoritesForCand) (*models.FavoriteID, error) {
	ret := _m.Called(_a0)

	var r0 *models.FavoriteID
	if rf, ok := ret.Get(0).(func(models.FavoritesForCand) *models.FavoriteID); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FavoriteID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.FavoritesForCand) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddRecommendation provides a mock function with given fields: _a0, _a1
func (_m *IUseCaseVacancy) AddRecommendation(_a0 uuid.UUID, _a1 int) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateVacancy provides a mock function with given fields: _a0
func (_m *IUseCaseVacancy) CreateVacancy(_a0 models.Vacancy) (*models.Vacancy, error) {
	ret := _m.Called(_a0)

	var r0 *models.Vacancy
	if rf, ok := ret.Get(0).(func(models.Vacancy) *models.Vacancy); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Vacancy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Vacancy) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteVacancy provides a mock function with given fields: id, empId
func (_m *IUseCaseVacancy) DeleteVacancy(id uuid.UUID, empId uuid.UUID) error {
	ret := _m.Called(id, empId)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(id, empId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCandFavoriteVacancy provides a mock function with given fields: candId
func (_m *IUseCaseVacancy) GetAllCandFavoriteVacancy(candId uuid.UUID) ([]models.BriefVacancyInfo, error) {
	ret := _m.Called(candId)

	var r0 []models.BriefVacancyInfo
	if rf, ok := ret.Get(0).(func(uuid.UUID) []models.BriefVacancyInfo); ok {
		r0 = rf(candId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BriefVacancyInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(candId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecommendation provides a mock function with given fields: _a0, _a1, _a2
func (_m *IUseCaseVacancy) GetRecommendation(_a0 uuid.UUID, _a1 int, _a2 int) ([]models.Vacancy, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 []models.Vacancy
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) []models.Vacancy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Vacancy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVacancy provides a mock function with given fields: _a0
func (_m *IUseCaseVacancy) GetVacancy(_a0 uuid.UUID) (*models.Vacancy, error) {
	ret := _m.Called(_a0)

	var r0 *models.Vacancy
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Vacancy); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Vacancy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVacancyList provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *IUseCaseVacancy) GetVacancyList(_a0 uint, _a1 uint, _a2 uuid.UUID, _a3 int) ([]models.Vacancy, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 []models.Vacancy
	if rf, ok := ret.Get(0).(func(uint, uint, uuid.UUID, int) []models.Vacancy); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Vacancy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, uint, uuid.UUID, int) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVacancyTopSpheres provides a mock function with given fields: _a0
func (_m *IUseCaseVacancy) GetVacancyTopSpheres(_a0 int32) ([]models.Sphere, *models.VacTopCnt, error) {
	ret := _m.Called(_a0)

	var r0 []models.Sphere
	if rf, ok := ret.Get(0).(func(int32) []models.Sphere); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Sphere)
		}
	}

	var r1 *models.VacTopCnt
	if rf, ok := ret.Get(1).(func(int32) *models.VacTopCnt); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.VacTopCnt)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(int32) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RemoveFavorite provides a mock function with given fields: _a0
func (_m *IUseCaseVacancy) RemoveFavorite(_a0 models.FavoritesForCand) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.FavoritesForCand) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchVacancies provides a mock function with given fields: _a0
func (_m *IUseCaseVacancy) SearchVacancies(_a0 models.VacancySearchParams) ([]models.Vacancy, error) {
	ret := _m.Called(_a0)

	var r0 []models.Vacancy
	if rf, ok := ret.Get(0).(func(models.VacancySearchParams) []models.Vacancy); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Vacancy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.VacancySearchParams) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVacancy provides a mock function with given fields: _a0
func (_m *IUseCaseVacancy) UpdateVacancy(_a0 models.Vacancy) (*models.Vacancy, error) {
	ret := _m.Called(_a0)

	var r0 *models.Vacancy
	if rf, ok := ret.Get(0).(func(models.Vacancy) *models.Vacancy); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Vacancy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Vacancy) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
