// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5d94b7ebDecodeGithubComGoParkMailRu20202MVVMGitModelsModels(in *jlexer.Lexer, out *Sphere) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "sphere_idx":
			out.Sph = int32(in.Int32())
		case "vac_cnt":
			out.VacCnt = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5d94b7ebEncodeGithubComGoParkMailRu20202MVVMGitModelsModels(out *jwriter.Writer, in Sphere) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sphere_idx\":"
		out.RawString(prefix[1:])
		out.Int32(int32(in.Sph))
	}
	{
		const prefix string = ",\"vac_cnt\":"
		out.RawString(prefix)
		out.Int32(int32(in.VacCnt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Sphere) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5d94b7ebEncodeGithubComGoParkMailRu20202MVVMGitModelsModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Sphere) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5d94b7ebEncodeGithubComGoParkMailRu20202MVVMGitModelsModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Sphere) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5d94b7ebDecodeGithubComGoParkMailRu20202MVVMGitModelsModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Sphere) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5d94b7ebDecodeGithubComGoParkMailRu20202MVVMGitModelsModels(l, v)
}
