// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	common "github.com/go-park-mail-ru/2020_2_MVVM.git/application/common"

	mock "github.com/stretchr/testify/mock"
)

// SessionBuilder is an autogenerated mock type for the SessionBuilder type
type SessionBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields: ctx
func (_m *SessionBuilder) Build(ctx *gin.Context) common.Session {
	ret := _m.Called(ctx)

	var r0 common.Session
	if rf, ok := ret.Get(0).(func(*gin.Context) common.Session); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Session)
		}
	}

	return r0
}
