// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	sessions "github.com/gin-contrib/sessions"
)

// SessionBuilder is an autogenerated mock type for the SessionBuilder type
type SessionBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields: ctx
func (_m *SessionBuilder) Build(ctx *gin.Context) sessions.Session {
	ret := _m.Called(ctx)

	var r0 sessions.Session
	if rf, ok := ret.Get(0).(func(*gin.Context) sessions.Session); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sessions.Session)
		}
	}

	return r0
}
