// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/go-park-mail-ru/2020_2_MVVM.git/application/models"
	mock "github.com/stretchr/testify/mock"
)

// CustomCompanyRepository is an autogenerated mock type for the CustomCompanyRepository type
type CustomCompanyRepository struct {
	mock.Mock
}

// CreateCustomCompany provides a mock function with given fields: resume
func (_m *CustomCompanyRepository) CreateCustomCompany(resume models.CustomCompany) (*models.CustomCompany, error) {
	ret := _m.Called(resume)

	var r0 *models.CustomCompany
	if rf, ok := ret.Get(0).(func(models.CustomCompany) *models.CustomCompany); ok {
		r0 = rf(resume)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CustomCompany)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.CustomCompany) error); ok {
		r1 = rf(resume)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomCompanyById provides a mock function with given fields: id
func (_m *CustomCompanyRepository) GetCustomCompanyById(id string) (*models.CustomCompany, error) {
	ret := _m.Called(id)

	var r0 *models.CustomCompany
	if rf, ok := ret.Get(0).(func(string) *models.CustomCompany); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CustomCompany)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
