// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package common

import mock "github.com/stretchr/testify/mock"

// MockRequest is an autogenerated mock type for the Request type
type MockRequest struct {
	mock.Mock
}
