// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAuthServer is an autogenerated mock type for the UnsafeAuthServer type
type UnsafeAuthServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAuthServer provides a mock function with given fields:
func (_m *UnsafeAuthServer) mustEmbedUnimplementedAuthServer() {
	_m.Called()
}
