// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/go-park-mail-ru/2020_2_MVVM.git/application/models"
	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: _a0
func (_m *UseCase) CreateUser(_a0 models.User) (*models.User, error) {
	ret := _m.Called(_a0)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(models.User) *models.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCandByID provides a mock function with given fields: id
func (_m *UseCase) GetCandByID(id string) (*models.User, error) {
	ret := _m.Called(id)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCandidateByID provides a mock function with given fields: id
func (_m *UseCase) GetCandidateByID(id string) (*models.Candidate, error) {
	ret := _m.Called(id)

	var r0 *models.Candidate
	if rf, ok := ret.Get(0).(func(string) *models.Candidate); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Candidate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEmplByID provides a mock function with given fields: id
func (_m *UseCase) GetEmplByID(id string) (*models.User, error) {
	ret := _m.Called(id)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEmployerByID provides a mock function with given fields: id
func (_m *UseCase) GetEmployerByID(id string) (*models.Employer, error) {
	ret := _m.Called(id)

	var r0 *models.Employer
	if rf, ok := ret.Get(0).(func(string) *models.Employer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Employer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: id
func (_m *UseCase) GetUserByID(id string) (*models.User, error) {
	ret := _m.Called(id)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: _a0
func (_m *UseCase) Login(_a0 models.UserLogin) (*models.User, error) {
	ret := _m.Called(_a0)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(models.UserLogin) *models.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.UserLogin) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEmployer provides a mock function with given fields: employer
func (_m *UseCase) UpdateEmployer(employer models.Employer) (*models.Employer, error) {
	ret := _m.Called(employer)

	var r0 *models.Employer
	if rf, ok := ret.Get(0).(func(models.Employer) *models.Employer); ok {
		r0 = rf(employer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Employer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Employer) error); ok {
		r1 = rf(employer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: user_id, newPassword, oldPassword, name, surname, email, phone, socialNetwork
func (_m *UseCase) UpdateUser(user_id string, newPassword string, oldPassword string, name string, surname string, email string, phone string, socialNetwork string) (*models.User, error) {
	ret := _m.Called(user_id, newPassword, oldPassword, name, surname, email, phone, socialNetwork)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string, string, string) *models.User); ok {
		r0 = rf(user_id, newPassword, oldPassword, name, surname, email, phone, socialNetwork)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string, string, string, string, string) error); ok {
		r1 = rf(user_id, newPassword, oldPassword, name, surname, email, phone, socialNetwork)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
