// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: api/vacancy.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Sphere struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sphere) Reset() {
	*x = Sphere{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vacancy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sphere) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sphere) ProtoMessage() {}

func (x *Sphere) ProtoReflect() protoreflect.Message {
	mi := &file_api_vacancy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sphere.ProtoReflect.Descriptor instead.
func (*Sphere) Descriptor() ([]byte, []int) {
	return file_api_vacancy_proto_rawDescGZIP(), []int{0}
}

type Vac struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
	Title           string `protobuf:"bytes,2,opt,name=Title,json=title,proto3" json:"Title,omitempty"`
	Gender          string `protobuf:"bytes,3,opt,name=Gender,json=gender,proto3" json:"Gender,omitempty"`
	SalaryMin       uint32 `protobuf:"varint,4,opt,name=SalaryMin,json=salaryMin,proto3" json:"SalaryMin,omitempty"`
	SalaryMax       uint32 `protobuf:"varint,5,opt,name=SalaryMax,json=salaryMax,proto3" json:"SalaryMax,omitempty"`
	Description     string `protobuf:"bytes,6,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	Requirements    string `protobuf:"bytes,7,opt,name=Requirements,json=requirements,proto3" json:"Requirements,omitempty"`
	Duties          string `protobuf:"bytes,8,opt,name=Duties,json=duties,proto3" json:"Duties,omitempty"`
	Skills          string `protobuf:"bytes,9,opt,name=Skills,json=skills,proto3" json:"Skills,omitempty"`
	Employment      string `protobuf:"bytes,10,opt,name=Employment,json=employment,proto3" json:"Employment,omitempty"`
	ExperienceMonth uint32 `protobuf:"varint,11,opt,name=ExperienceMonth,json=experienceMonth,proto3" json:"ExperienceMonth,omitempty"`
	Location        string `protobuf:"bytes,12,opt,name=Location,json=location,proto3" json:"Location,omitempty"`
	AreaSearch      string `protobuf:"bytes,13,opt,name=AreaSearch,json=areaSearch,proto3" json:"AreaSearch,omitempty"`
	CareerLevel     string `protobuf:"bytes,14,opt,name=CareerLevel,json=careerLevel,proto3" json:"CareerLevel,omitempty"`
	EducationLevel  string `protobuf:"bytes,15,opt,name=EducationLevel,json=educationLevel,proto3" json:"EducationLevel,omitempty"`
	EmpEmail        string `protobuf:"bytes,16,opt,name=EmpEmail,json=empEmail,proto3" json:"EmpEmail,omitempty"`
	EmpPhone        string `protobuf:"bytes,17,opt,name=EmpPhone,json=empPhone,proto3" json:"EmpPhone,omitempty"`
	Sphere          string `protobuf:"bytes,18,opt,name=Sphere,json=sphere,proto3" json:"Sphere,omitempty"`
}

func (x *Vac) Reset() {
	*x = Vac{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vacancy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vac) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vac) ProtoMessage() {}

func (x *Vac) ProtoReflect() protoreflect.Message {
	mi := &file_api_vacancy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vac.ProtoReflect.Descriptor instead.
func (*Vac) Descriptor() ([]byte, []int) {
	return file_api_vacancy_proto_rawDescGZIP(), []int{1}
}

func (x *Vac) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vac) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Vac) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Vac) GetSalaryMin() uint32 {
	if x != nil {
		return x.SalaryMin
	}
	return 0
}

func (x *Vac) GetSalaryMax() uint32 {
	if x != nil {
		return x.SalaryMax
	}
	return 0
}

func (x *Vac) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Vac) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *Vac) GetDuties() string {
	if x != nil {
		return x.Duties
	}
	return ""
}

func (x *Vac) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *Vac) GetEmployment() string {
	if x != nil {
		return x.Employment
	}
	return ""
}

func (x *Vac) GetExperienceMonth() uint32 {
	if x != nil {
		return x.ExperienceMonth
	}
	return 0
}

func (x *Vac) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Vac) GetAreaSearch() string {
	if x != nil {
		return x.AreaSearch
	}
	return ""
}

func (x *Vac) GetCareerLevel() string {
	if x != nil {
		return x.CareerLevel
	}
	return ""
}

func (x *Vac) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *Vac) GetEmpEmail() string {
	if x != nil {
		return x.EmpEmail
	}
	return ""
}

func (x *Vac) GetEmpPhone() string {
	if x != nil {
		return x.EmpPhone
	}
	return ""
}

func (x *Vac) GetSphere() string {
	if x != nil {
		return x.Sphere
	}
	return ""
}

type VacId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
}

func (x *VacId) Reset() {
	*x = VacId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vacancy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VacId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacId) ProtoMessage() {}

func (x *VacId) ProtoReflect() protoreflect.Message {
	mi := &file_api_vacancy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacId.ProtoReflect.Descriptor instead.
func (*VacId) Descriptor() ([]byte, []int) {
	return file_api_vacancy_proto_rawDescGZIP(), []int{2}
}

func (x *VacId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vacancy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_vacancy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_vacancy_proto_rawDescGZIP(), []int{3}
}

var File_api_vacancy_proto protoreflect.FileDescriptor

var file_api_vacancy_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x08, 0x0a, 0x06, 0x53, 0x70, 0x68, 0x65,
	0x72, 0x65, 0x22, 0x95, 0x04, 0x0a, 0x03, 0x76, 0x61, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x61, 0x6c, 0x61,
	0x72, 0x79, 0x4d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x61, 0x6c,
	0x61, 0x72, 0x79, 0x4d, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79,
	0x4d, 0x61, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x61, 0x6c, 0x61, 0x72,
	0x79, 0x4d, 0x61, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x75,
	0x74, 0x69, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x75, 0x74, 0x69,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x45, 0x78,
	0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x4d,
	0x6f, 0x6e, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x72, 0x65, 0x61, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x72, 0x65, 0x61, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x12, 0x20, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x65, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x64, 0x75, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x6d,
	0x70, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6d,
	0x70, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6d, 0x70, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x70, 0x68, 0x65, 0x72, 0x65, 0x18, 0x12, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x70, 0x68, 0x65, 0x72, 0x65, 0x22, 0x17, 0x0a, 0x05, 0x76, 0x61,
	0x63, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x56, 0x0a, 0x07,
	0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x25, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x08, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x61, 0x63, 0x1a, 0x08, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x61, 0x63, 0x22, 0x00, 0x12, 0x24,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x0a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x61, 0x63, 0x49, 0x64, 0x1a, 0x08, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x61, 0x63, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_vacancy_proto_rawDescOnce sync.Once
	file_api_vacancy_proto_rawDescData = file_api_vacancy_proto_rawDesc
)

func file_api_vacancy_proto_rawDescGZIP() []byte {
	file_api_vacancy_proto_rawDescOnce.Do(func() {
		file_api_vacancy_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_vacancy_proto_rawDescData)
	})
	return file_api_vacancy_proto_rawDescData
}

var file_api_vacancy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_vacancy_proto_goTypes = []interface{}{
	(*Sphere)(nil), // 0: api.Sphere
	(*Vac)(nil),    // 1: api.vac
	(*VacId)(nil),  // 2: api.vacId
	(*Empty)(nil),  // 3: api.empty
}
var file_api_vacancy_proto_depIdxs = []int32{
	1, // 0: api.Vacancy.CreateVacancy:input_type -> api.vac
	2, // 1: api.Vacancy.GetVacancy:input_type -> api.vacId
	1, // 2: api.Vacancy.CreateVacancy:output_type -> api.vac
	1, // 3: api.Vacancy.GetVacancy:output_type -> api.vac
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_vacancy_proto_init() }
func file_api_vacancy_proto_init() {
	if File_api_vacancy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_vacancy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sphere); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vacancy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vac); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vacancy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VacId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vacancy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_vacancy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_vacancy_proto_goTypes,
		DependencyIndexes: file_api_vacancy_proto_depIdxs,
		MessageInfos:      file_api_vacancy_proto_msgTypes,
	}.Build()
	File_api_vacancy_proto = out.File
	file_api_vacancy_proto_rawDesc = nil
	file_api_vacancy_proto_goTypes = nil
	file_api_vacancy_proto_depIdxs = nil
}
