// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// VacancyClient is the client API for Vacancy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VacancyClient interface {
	CreateVacancy(ctx context.Context, in *Vac, opts ...grpc.CallOption) (*Vac, error)
	//rpc UpdateVacancy(vacReq) returns (*models.Vacancy, error)
	GetVacancy(ctx context.Context, in *VacId, opts ...grpc.CallOption) (*Empty, error)
}

type vacancyClient struct {
	cc grpc.ClientConnInterface
}

func NewVacancyClient(cc grpc.ClientConnInterface) VacancyClient {
	return &vacancyClient{cc}
}

func (c *vacancyClient) CreateVacancy(ctx context.Context, in *Vac, opts ...grpc.CallOption) (*Vac, error) {
	out := new(Vac)
	err := c.cc.Invoke(ctx, "/api.Vacancy/CreateVacancy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyClient) GetVacancy(ctx context.Context, in *VacId, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Vacancy/GetVacancy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VacancyServer is the server API for Vacancy service.
// All implementations must embed UnimplementedVacancyServer
// for forward compatibility
type VacancyServer interface {
	CreateVacancy(context.Context, *Vac) (*Vac, error)
	//rpc UpdateVacancy(vacReq) returns (*models.Vacancy, error)
	GetVacancy(context.Context, *VacId) (*Empty, error)
	mustEmbedUnimplementedVacancyServer()
}

// UnimplementedVacancyServer must be embedded to have forward compatible implementations.
type UnimplementedVacancyServer struct {
}

func (UnimplementedVacancyServer) CreateVacancy(context.Context, *Vac) (*Vac, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVacancy not implemented")
}
func (UnimplementedVacancyServer) GetVacancy(context.Context, *VacId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVacancy not implemented")
}
func (UnimplementedVacancyServer) mustEmbedUnimplementedVacancyServer() {}

// UnsafeVacancyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VacancyServer will
// result in compilation errors.
type UnsafeVacancyServer interface {
	mustEmbedUnimplementedVacancyServer()
}

func RegisterVacancyServer(s grpc.ServiceRegistrar, srv VacancyServer) {
	s.RegisterService(&_Vacancy_serviceDesc, srv)
}

func _Vacancy_CreateVacancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vac)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServer).CreateVacancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vacancy/CreateVacancy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServer).CreateVacancy(ctx, req.(*Vac))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vacancy_GetVacancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VacId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServer).GetVacancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vacancy/GetVacancy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServer).GetVacancy(ctx, req.(*VacId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vacancy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Vacancy",
	HandlerType: (*VacancyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVacancy",
			Handler:    _Vacancy_CreateVacancy_Handler,
		},
		{
			MethodName: "GetVacancy",
			Handler:    _Vacancy_GetVacancy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/vacancy.proto",
}
